ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" # noqa: var-naming
imagebuilder_envfile_path: "{{ '~/.template_builder/env.sh' | expanduser }}"
imagebuilder_useauxiso: false
imagebuilder_prefix_port_offset_map:
    alma: 0
    ol: 1
    rocky: 2
    debian: 3
    ubuntu: 4
    windows: 5
    suse: 6
    fedora: 7
    centos: 8
    rhel: 9
    leap: 10
imagebuilder_prefix_ostype_map:
    alma: linux
    ol: linux
    rocky: linux
    debian: linux
    ubuntu: linux
    windows: windows
    suse: linux
    fedora: linux
    centos: linux
    rhel: linux
    leap: linux
imagebuilder_prefix_variant_map:
    alma: almalinux
    ol: oraclelinux
    rocky: rockylinux
    debian: debian
    ubuntu: ubuntu
    windows: windows
    suse: sles
    fedora: fedora
    centos: centos
    rhel: rhel
    leap: leap
imagebuilder_port_offset: "{{ imagebuilder_prefix_port_offset_map[imagebuilder_id_prefix] }}"
imagebuilder_localport: "{{ 8180 + (imagebuilder_port_offset | default(0) | int) }}"
imagebuilder_package_lists:
    debian:
        - software-properties-common
        - ansible
        - genisoimage
        - ipxe-qemu
        - qemu-system-x86
        - qemu-system-common
        - qemu-system-data
        - qemu-utils
        - netcat-openbsd
        - sshpass
        - unzip
        - vim
        - wget
        - xorriso
        - libxml2-dev
        - libxslt-dev
        - python3-dev
        - libnbd-bin
        - nbdkit
        - guestfish
        - python3-pip

    fedora:
        - libguestfs-tools-c
        - libguestfs-tools
        - supermin
        - qemu-system-x86-core
        - qemu-img
        - dracut
        - python3
        - python3-pip
        - python3-virtualenv
        - python3-devel
        - libxml2-devel
        - libxslt-devel
        - gcc
        - gcc-c++
        - make
        - openssh-clients
        - git
        - jq
        - tar
        - gzip
        - sudo
        - curl
        - xorriso
        - nbdkit
        - genisoimage
        - ipxe-bootimgs
        - vim

imagebuilder_pip_packages:
    debian:
        - pywinrm
        - proxmoxer
        - ovirt-engine-sdk-python

    fedora:
        - pywinrm
        - proxmoxer
        - ovirt-engine-sdk-python

imagebuilder_base_qemu_command: "qemu-system-x86_64"

# default build steps

imagebuilder_build_default:
    - name: buildaux
    - name: buildimage
    - name: patching
      task_vars:
          location: internet
          sub_tasks:
              - "prepare"
              - "patch"
              - "cleanup"
    - name: hardening
    - name: template-cleanup
