ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" # noqa: var-naming
imagebuilder_envfile_path: "{{ '~/.template_builder/env.sh' | expanduser }}"
imagebuilder_useauxiso: false
imagebuilder_localip: "{{ ansible_facts['default_ipv4']['address'] | default('localhost') }}"
imagebuilder_prefix_port_offset_map:
    alma: 0
    ol: 1
    rocky: 2
    debian: 3
    ubuntu: 4
    windows: 5
    suse: 6
    fedora: 7
    centos: 8
    rhel: 9
    leap: 10
imagebuilder_port_offset: "{{ imagebuilder_prefix_port_offset_map[imagebuilder_id_prefix] }}"
imagebuilder_localport: "{{ 8180 + (imagebuilder_port_offset | default(0) | int) }}"
imagebuilder_package_lists:
    debian:
        - software-properties-common
        - ansible
        - genisoimage
        - ipxe-qemu
        - qemu-system-x86
        - qemu-system-common
        - qemu-system-data
        - qemu-utils
        - netcat-openbsd
        - sshpass
        - unzip
        - vim
        - wget
        - xorriso
        - libxml2-dev
        - libxslt-dev
        - python3-dev
        - libnbd-bin
        - nbdkit
        - guestfish
        - python3-pip
imagebuilder_pip_packages:
    debian:
        - pywinrm
        - proxmoxer
        - ovirt-engine-sdk-python
imagebuilder_base_qemu_command: "qemu-system-x86_64"

# default build steps

imagebuilder_build_default:
    - name: download
      task_vars:
          download_url: "{{ os.iso }}"
          download_checksum: "{{ os.checksum }}"
          download_dest: "{{ imagebuilder_build_basedir }}/downloads/{{ os.iso | basename }}"
    - name: buildaux
    - name: buildimage
    - name: patching
      task_vars:
          location: internet
          sub_tasks:
              - "prepare"
              - "patch"
              - "cleanup"
    - name: hardening
    - name: template-cleanup
    # - name: target-proxmox
    # - name: target-ovirt
