builder_useauxiso: false
builder_localip: "{{ ansible_facts['default_ipv4']['address'] | default('localhost') }}"
builder_prefix_port_offset_map:
    alma: 0
    ol: 1
    rocky: 2
    debian: 3
    ubuntu: 4
    windows: 5
    suse: 6
    fedora: 7
    centos: 8
    rhel: 9
    leap: 10

builder_package_lists:
    debian:
        - software-properties-common
        - ansible
        - genisoimage
        - ipxe-qemu
        - qemu-system-x86
        - qemu-system-common
        - qemu-system-data
        - qemu-utils
        - netcat-openbsd
        - sshpass
        - unzip
        - vim
        - wget
        - xorriso
        - libxml2-dev
        - libxslt-dev
        - python3-dev
        - libnbd-bin
        - nbdkit
        - guestfish
        - python3-pip
builder_pip_packages:
    debian:
        - pywinrm
        - proxmoxer
        - ovirt-engine-sdk-python
builder_base_qemu_command: "qemu-system-x86_64"

# default build steps

builder_build_default:
    - name: download
      task_vars:
          download_url: "{{ os.iso }}"
          download_checksum: "{{ os.checksum }}"
          download_dest: "{{ builder_build_basedir }}/downloads/{{ os.iso | basename }}"
    - name: buildaux
    - name: buildimage
    - name: patching
      task_vars:
          location: internet
          sub_tasks:
              - "prepare"
              - "patch"
              - "cleanup"
    - name: hardening
    - name: template-cleanup
    # - name: target-proxmox
    # - name: target-ovirt
