---
- name: (BUILDPROFILE) Include build profile implementation
  tags:
      - always
  block:
      - name: (BUILDPROFILE) include variant-specific tasks
        ansible.builtin.include_tasks:
            file: buildprofile/{{ os.variant | lower }}.yml
        when: os.variant is defined
