---
- name: (MAIN)Expand standard credentials file path
  ansible.builtin.set_fact:
    envfile_path: "{{ '~/.template_builder/credentials.sh' | expanduser }}" # noqa: var-naming

- name: (MAIN) Check if credentials file exists in the standard location
  ansible.builtin.stat:
    path: "{{ envfile_path }}"
  register: envfile_stat # noqa: var-naming

- name: (MAIN) Load env file (a=b format)
  ansible.builtin.slurp:
    src: "{{ envfile_path }}"
  register: raw_env # noqa: var-naming
  when: envfile_stat.stat.exists

- name: (MAIN) Convert env file to dict
  ansible.builtin.set_fact:
    builder_env: # noqa: var-naming
      >-
        {{
          raw_env.content
          | b64decode
          | regex_replace('^\\s*#.*$', '', multiline=True)
          | regex_replace('^\\s*$', '', multiline=True)
          | regex_replace('=', ': ', multiline=True)
          | from_yaml
        }}
  when: envfile_stat.stat.exists

- name: (MAIN) Display loaded environment variables
  ansible.builtin.debug:
    var: builder_env
  when: builder_env is defined

- name: (MAIN) Map builder_env.* into individual vars
  ansible.builtin.set_fact:
    builder_env_qemu_ip: "{{ builder_env.BUILDER_ENV_QEMU_IP }}" # noqa: var-naming
    builder_env_build_path: "{{ builder_env.BUILDER_ENV_BUILD_PATH }}" # noqa: var-naming
    builder_env_ansible_user: "{{ builder_env.BUILDER_ENV_ANSIBLE_USER }}" # noqa: var-naming
    builder_env_ansible_password: "{{ builder_env.BUILDER_ENV_ANSIBLE_PASSWORD }}" # noqa: var-naming
    builder_env_linux_admin_user: "{{ builder_env.BUILDER_ENV_LINUX_ADMIN_USER }}" # noqa: var-naming
    builder_env_linux_admin_password: "{{ builder_env.BUILDER_ENV_LINUX_ADMIN_PASSWORD }}" # noqa: var-naming
    builder_env_win_admin_user: "{{ builder_env.BUILDER_ENV_WIN_ADMIN_USER }}" # noqa: var-naming
    builder_env_win_admin_password: "{{ builder_env.BUILDER_ENV_WIN_ADMIN_PASSWORD }}" # noqa: var-naming
    builder_env_ansible_key: "{{ builder_env.BUILDER_ENV_ANSIBLE_KEY }}" # noqa: var-naming
  when: envfile_stat.stat.exists


- name: (MAIN) Assert required build variables are defined
  ansible.builtin.assert:
    that:
      - builder_env_qemu_ip is defined and builder_env_qemu_ip | trim | length > 0
      - builder_env_build_path is defined and builder_env_build_path and (builder_env_build_path | trim | length > 0)
      - builder_env_ansible_user is defined and builder_env_ansible_user and (builder_env_ansible_user | trim | length > 0)
      - builder_env_ansible_password is defined and builder_env_ansible_password and (builder_env_ansible_password | trim | length > 0)
      - builder_env_linux_admin_user is defined and builder_env_linux_admin_user and (builder_env_linux_admin_user | trim | length > 0)
      - builder_env_linux_admin_password is defined and builder_env_linux_admin_password and (builder_env_linux_admin_password | trim | length > 0)
      - builder_env_win_admin_user is defined and builder_env_win_admin_user and (builder_env_win_admin_user | trim | length > 0)
      - builder_env_win_admin_password is defined and builder_env_win_admin_password and (builder_env_win_admin_password | trim | length > 0)
      - builder_env_ansible_key is defined and builder_env_ansible_key and (builder_env_ansible_key | trim | length > 0)
    fail_msg: "(MAIN) One or more required variables are not defined correctly."
    success_msg: "(MAIN) All required variables are defined and appear valid."
  tags:                       # list all the tags used role wide so we can see them with a list-tags command
    - always
    - build_targets
    - build_target_proxmox
    - build_target_ovirt
    - build_fetch_iso
    - build_base
    - build_aux
    - build_customise
    - build_cleanup
- name: (MAIN) Drive Setup
  ansible.builtin.include_role:
    name: imagebuilder
    tasks_from: setup
  tags:
    - always


- name: (MAIN) add default build steps if none are defined
  ansible.builtin.set_fact:
    build: "{{ builder_build_default }}" # noqa: var-naming[no-role-prefix]
  when: build is not defined or build | length == 0
  tags:
    - always
- name: (MAIN) Perform the build
  block:
    - name: (MAIN) include build roles if any are defined
      ansible.builtin.include_role:
        name: imagebuilder
        tasks_from: "glue/glue.yml"
      tags:
        - always
      vars:
        builder_stage: "{{ builder_buildtask.name }}" # noqa: var-naming
        builder_task_vars: "{{ builder_buildtask.task_vars | default({}) }}" # noqa: var-naming
      loop: "{{ build | default([]) }}"
      loop_control:
        loop_var: builder_buildtask
    - name: (MAIN) cleanup build path
      ansible.builtin.file:
        path: "{{ builder_env_build_path }}/{{ builder_build_id }}"
        state: absent
      become: true
      tags:
        - build_cleanup
  rescue:
    - name: "(MAIN) Show error on failure"
      ansible.builtin.debug:
        msg: >-
          (MAIN) Task '{{ ansible_failed_task }}' failed.
          {{ ansible_failed_result.msg | default('no additional message') }}
      tags:
        - always
  always:
    - name: (MAIN) Display Webserver job_id
      ansible.builtin.debug:
        msg: "(MAIN) Webserver jobid is {{ webserver.ansible_job_id }} "
      when: webserver is defined and webserver.ansible_job_id is defined
      tags:
        - always
    - name: (MAIN) kill dangly web servers
      ansible.builtin.shell: |
        kill {{ webserver.ansible_job_pid | default('') }} 2>/dev/null || true
        sleep 5
        kill -9 {{ webserver.ansible_job_pid | default('') }} 2>/dev/null || true
      when: webserver is defined and webserver.ansible_job_pid is defined
      changed_when: false
      tags:
        - always
