- name: (QEMU) Set Template
  block:
    - name: (QEMU) Set QEMU arguments
      ansible.builtin.set_fact:
        qemu_args: # noqa: var-naming
          - "-name {{ id }}"
          - "-enable-kvm"
          - "-cpu host"
          - "-smp {{ imagebuilder_build_vcpus }}"
          - "-m {{ imagebuilder_build_ram }}"
          - "-netdev user,id=net0,hostfwd=tcp:0.0.0.0:{{ (os_type | lower == 'linux') | ternary(imagebuilder_env_qemu_ssh_port, imagebuilder_env_qemu_psrp_port) }}-:{{ (os_type | lower == 'windows') | ternary(5986, 22) }}"
          - "-device {{ os.config.nicdriver | default('e1000') }},netdev=net0"
          - "-device ich9-ahci,id=ahci"
          - "-drive file={{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2,media=disk,if=none,format=qcow2,id=disk0"
          - "-device ide-hd,drive=disk0,bus=ahci.0"
          - "-vnc 0.0.0.0:{{ imagebuilder_port_offset }}"


    - name: (QEMU) Set QEMU command
      ansible.builtin.set_fact:
        imagebuilder_qemu_command: "{{ imagebuilder_base_qemu_command }} {{ qemu_args | join(' ') }}"

    - name: (QEMU) Set QEMU command with aux ISO if needed
      ansible.builtin.set_fact:
        imagebuilder_qemu_command: "{{ imagebuilder_qemu_command }} -drive file={{ imagebuilder_build_imagedir }}/aux.iso,media=cdrom,if=ide,index=2"
      when: useauxiso | default(false) | bool

    - name: (QEMU) Start temporary web server
      ansible.builtin.shell: |
        python3 -m http.server {{ imagebuilder_localport }} --directory {{ imagebuilder_build_httpdir }}
      async: 3600        # max runtime in seconds
      poll: 0            # run in background
      register: webserver # noqa: var-naming
      changed_when: true

    - name: (QEMU) Build base
      when:
        - not imagebuilder_restored_from_image | default(false) | bool
      block:
        - name: (QEMU) Launch QEMU VM
          ansible.builtin.command: >
              {{ imagebuilder_qemu_command }} \
              -chardev socket,id=mon0,host=localhost,port={{ imagebuilder_env_qemu_monport }},server=on,wait=off \
              -mon chardev=mon0, \
              -boot order=d \
              -drive file="{{ imagebuilder_build_iso }}",media=cdrom,if=ide,index=1
          async: 99999
          changed_when: true
          poll: 0
          register: qemu_boot # noqa: var-naming

        - name: "(QEMU) Wait for QEMU monitor"
          ansible.builtin.wait_for:
            port: "{{ imagebuilder_env_qemu_monport }}"
            delay: 5
            timeout: 120
        - name: "(QEMU) Show console boot commands"
          ansible.builtin.debug: msg="{{ os.console_boot | map('string') | join('') }}" # noqa: no-free-form
          when:
            - os.console_boot is defined
        - name: "(QEMU) Run sendkeys script to send commands to QEMU monitor"
          vars:
            sendkeys_script: "{{ imagebuilder_build_basedir }}/sendkeys.py"
            sendkeys_commands: "{{ os.console_boot }}"
          ansible.builtin.command:
            argv:
              - python3
              - "{{ imagebuilder_build_basedir }}/sendkeys.py"
              - --host
              - localhost
              - --port
              - "{{ imagebuilder_env_qemu_monport }}"
              - --boot-command
              - "{{ os.console_boot }}"
          delegate_to: "{{ run_on | default('localhost') }}"
          changed_when: true
          register: sendkeys_result # noqa: var-naming
          when:
            - os.console_boot is defined
        - name: "(QEMU) Show sendkeys result"
          ansible.builtin.debug:
            msg: "{{ sendkeys_result }}"
          when:
            - os.console_boot is defined

        - name: "(QEMU) Wait for QEMU monitor"
          ansible.builtin.wait_for:
            port: "{{ imagebuilder_env_qemu_monport }}"
            delay: 20
            timeout: 120

        - name: "(QEMU) Wait for QEMU async job to finish (poll process)"
          ansible.builtin.shell: |
            max_retries=600
            count=0
            while pgrep -f "^qemu.*{{ id }}.x86_64.qcow2" >/dev/null 2>&1; do
              sleep 10
              count=$((count+1))
              if [ "$count" -ge "$max_retries" ]; then
                echo "timeout waiting for qemu process to exit"
                exit 2
              fi
            done
            exit 0
          register: qemu_wait # noqa: var-naming
          failed_when: qemu_wait.rc != 0
          changed_when: false
          delegate_to: "{{ run_on | default('localhost') }}"
          tags:
            - build_base

        - name: (QEMU) save base image
          block:
            # Ensure qcow2 is not open by any process
            - name: Check for open handles on qcow2
              ansible.builtin.shell: |
                  lsof "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2" || true
              changed_when: false
              register: imagebuilder_qcow2_lsof

            - name: Fail if qcow2 is still open
              ansible.builtin.fail:
                msg: "qcow2 still open by a process: {{ imagebuilder_qcow2_lsof.stdout }}"
              when: imagebuilder_qcow2_lsof.stdout != ""

            # Flush host page cache before conversion
            - name: Sync host filesystem
              ansible.builtin.command: "sync"
              changed_when: false

            - name: (QEMU) convert base image with free block cleanup
              ansible.builtin.command: qemu-img convert -f qcow2 -O qcow2 "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2" "{{ imagebuilder_build_savedir }}/{{ id }}.base.{{ imagebuilder_profile_hash }}.qcow2.tmp"
              changed_when: true

            - name: (QEMU) finalize base image
              ansible.builtin.command: mv "{{ imagebuilder_build_savedir }}/{{ id }}.base.{{ imagebuilder_profile_hash }}.qcow2.tmp" "{{ imagebuilder_build_savedir }}/{{ id }}.base.{{ imagebuilder_profile_hash }}.qcow2"
              changed_when: true


  rescue:
    - name: "(QEMU) Show error on failure"
      ansible.builtin.debug:
        msg: >-
          (QEMU) Task '{{ ansible_failed_task }}' failed.
          {{ ansible_failed_result.msg | default('no additional message') }}
      tags:
        - always
  always:
    - name: (QEMU) Cleanup temporary webserver + dangling QEMU
      ansible.builtin.shell: |
        set -o pipefail;
        # Kill webserver (TERM only)
        pgrep -f "python3 -m http.server {{ imagebuilder_localport }}" \
          | xargs -r kill -15 2>/dev/null || true

        # Kill QEMU (TERM -> wait -> KILL)
        pgrep -f "^{{ imagebuilder_base_qemu_command }}.*{{ id }}" \
          | xargs -r kill -15 2>/dev/null || true

        sleep 5

        pgrep -f "^{{ imagebuilder_base_qemu_command }}.*{{ id }}" \
          | xargs -r kill -9 2>/dev/null || true
      changed_when: true
      failed_when: false
