- name: (RESTORE) delete any existing (in-progress) QEMU VM disk image
  ansible.builtin.file:
    path: "{{ qemufile }}"
    state: absent
  loop_control:
    loop_var: qemufile
  loop:
    - "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2"

- name: (RESTORE) stat any saved custom image
  ansible.builtin.stat:
    path: "{{ imagebuilder_build_savedir }}/{{ id }}.custom.{{ imagebuilder_profile_hash }}.qcow2"
  register: imagebuilder_qemu_disk_custom_stat

- name: (RESTORE) stat any saved base image
  ansible.builtin.stat:
    path: "{{ imagebuilder_build_savedir }}/{{ id }}.base.{{ imagebuilder_profile_hash }}.qcow2"
  register: imagebuilder_qemu_disk_base_stat

- name: (RESTORE) restore custom image if it exists and is newer than base image
  ansible.builtin.command: cp "{{ imagebuilder_build_savedir }}/{{ id }}.custom.{{ imagebuilder_profile_hash }}.qcow2" "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2"
  changed_when: imagebuilder_qemu_disk_restore.rc == 0
  failed_when: imagebuilder_qemu_disk_restore.rc != 0
  when:
    - imagebuilder_qemu_disk_custom_stat.stat.exists
    - imagebuilder_qemu_disk_custom_stat.stat.size > 0
    - not imagebuilder_qemu_disk_base_stat.stat.exists or imagebuilder_qemu_disk_custom_stat.stat.mtime > imagebuilder_qemu_disk_base_stat.stat.mtime
  register: imagebuilder_qemu_disk_restore

- name: (RESTORE) record we restored from a custom image
  when: imagebuilder_qemu_disk_restore is defined and imagebuilder_qemu_disk_restore.changed
  ansible.builtin.set_fact:
    imagebuilder_restored_from_image: true
    imagebuilder_restored_from_custom_image: true
    imagebuilder_restored_from_base_image: false
    imagebuilder_banner_message: "Restored custom image from {{ imagebuilder_build_savedir }}/{{ id }}.custom.{{ imagebuilder_profile_hash }}.qcow2"

- name: (RESTORE) Base Image Exists?
  when: not imagebuilder_restored_from_image
  block:
    - name: (RESTORE) restore base image if it exists
      ansible.builtin.command: cp "{{ imagebuilder_build_savedir }}/{{ id }}.base.{{ imagebuilder_profile_hash }}.qcow2" "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2"
      changed_when: imagebuilder_qemu_disk_restore is defined and imagebuilder_qemu_disk_restore.rc == 0
      failed_when: imagebuilder_qemu_disk_restore.rc != 0
      when:
        - imagebuilder_qemu_disk_base_stat.stat.exists
        - imagebuilder_qemu_disk_base_stat.stat.size > 0
      register: imagebuilder_qemu_disk_restore

    - name: (RESTORE) record we restored from a base image
      when: imagebuilder_qemu_disk_restore is defined and imagebuilder_qemu_disk_restore.changed
      ansible.builtin.set_fact:
        imagebuilder_restored_from_image: true
        imagebuilder_restored_from_custom_image: false
        imagebuilder_restored_from_base_image: true
        imagebuilder_banner_message: "Restored base image from {{ imagebuilder_build_savedir }}/{{ id }}.base.{{ imagebuilder_profile_hash }}.qcow2"

- name: (RESTORE) Show restored base result
  when: imagebuilder_restored_from_image | default(false) | bool
  ansible.builtin.include_tasks: banner.yml

- name: (RESTORE) if no image was restored, create an empty disk for the build
  when: not imagebuilder_restored_from_image
  block:
    - name: (RESTORE) Create VM disk image
      ansible.builtin.command: qemu-img create -f qcow2 "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2" "{{ os.config.disks[0] }}G"
      args:
        creates: "{{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2"
      register: imagebuilder_qemu_disk
      failed_when: imagebuilder_qemu_disk.rc != 0
      changed_when: imagebuilder_qemu_disk.rc == 0

    - name: (RESTORE) Show disk creation result
      ansible.builtin.include_tasks: banner.yml
      vars:
        imagebuilder_banner_message: "Created disk at {{ imagebuilder_build_imagedir }}/{{ id }}.x86_64.qcow2 with size {{ os.config.disks[0] }}G"
