---
- name: (PATCHING) Setup variables and facts
  tags:
    - always
  block:

    - name: (PATCHING-CLEANUP) Cleanup
      ansible.builtin.include_tasks: "cleanup/{{ ansible_facts['os_family'] }}.yml"
