---
- name: (PATCHING) Setup variables and facts
  tags:
    - always
  block:
    - name: (PATCHING) do a setup
      ansible.builtin.setup:
      delegate_to: "{{ delegate | default(omit) }}"
    - name: (PATCHING) If we were provided a run list then follow it.
      ansible.builtin.include_tasks: "patching/{{ nexttask }}.yml"
      loop: "{{ sub_tasks | default([]) }}"
      loop_control:
        loop_var: nexttask
      when: sub_tasks is defined

    - name: (PATCHING) do a standard patch unless a runlist has been provided
      ansible.builtin.include_tasks: "patching/patch.yml"
      when: sub_tasks is not defined
