---
argument_specs:
  main:
    short_description: CentOS Linux imagebuilder OS plugin

    options:
      os:
        type: dict
        required: true

      imagebuilder_config:
        type: dict
        required: true
