---
# Ubuntu-Based Systems
- name: (BUILDPROFILE, ubuntu)
  tags:
      - build_aux
  block:
      - name: (BUILDPROFILE, ubuntu) create build directories
        ansible.builtin.file:
            path: "{{ file }}"
            state: directory
            mode: "0755"
        loop_control:
            loop_var: file
        loop:
            - "{{ imagebuilder_build_basedir }}/build"
            - "{{ imagebuilder_build_basedir }}/build/mnt"


      - name: (BUILDPROFILE, ubuntu) remove existing aux ISO (if it exists)
        ansible.builtin.file:
            path: "{{ imagebuilder_build_basedir }}/build/aux.iso"
            state: absent

      - name: (BUILDPROFILE, ubuntu) create temporary iso contents dir
        ansible.builtin.file:
            path: "{{ imagebuilder_build_basedir }}/build/iso_contents"
            mode: "0755"
            state: directory

      - name: (BUILDPROFILE, ubuntu) Generate hashed password (Ubuntu)
        ansible.builtin.shell: "set -o pipefail; printf '{{ imagebuilder_env_ansible_password }}' | openssl passwd -6 -stdin"
        register: hashed_password # noqa: var-naming
        changed_when: false

      - name: (BUILDPROFILE, ubuntu) Set hashed password fact (Ubuntu)
        ansible.builtin.set_fact:
            hashed_password: "{{ hashed_password.stdout }}" # noqa: var-naming

      - name: (BUILDPROFILE, ubuntu) use default metadata if none provided
        ansible.builtin.set_fact:
            metadata: "" # noqa: var-naming
        when: metadata is not defined
      - name: (BUILDPROFILE, ubuntu) use default userdata if none provided
        ansible.builtin.set_fact:
            userdata: # noqa: var-naming
                |
                  #cloud-config
                  autoinstall:
                    version: 1
                    shutdown: poweroff

                    storage:
                      layout:
                        name: lvm
                        sizing-policy: all
                      match:
                        size: largest

                    locale: en_AU.UTF-8
                    keyboard:
                      layout: us

                    identity:
                      hostname: {{ imagebuilder_id_base }}
                      username: {{ imagebuilder_env_ansible_user }}
                      password: "{{ hashed_password }}"

                    ssh:
                      allow-pw: true
                      install-server: true

                    apt:
                      primary:
                        - arches: [default]
                          uri: file:///cdrom
                      disable_components: []
                      disable_suites: []

                    packages:
                      - openssh-server

                    late-commands:
                      - rm -f /target/etc/netplan/*.yaml
                      - |
                        cat <<EOF >/target/etc/netplan/01-netcfg.yaml
                        network:
                          version: 2
                          renderer: networkd
                        EOF

                      - |
                        cat <<EOF | sudo tee /target/etc/sudoers.d/{{ imagebuilder_env_ansible_user }}
                        {{ imagebuilder_env_ansible_user }}  ALL=(ALL)       NOPASSWD: ALL
                        EOF

                      - curtin in-target --target /target netplan generate
                      - curtin in-target --target /target netplan apply

                  # -------------------------------
                  # Cloud-init section (top-level)
                  # -------------------------------

                  user-data:
                    runcmd:
                      - ssh-keygen -A
                      - systemctl enable ssh

                  users:
                    - name: {{ imagebuilder_env_ansible_user }}
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      shell: /bin/bash

                  chpasswd:
                    list: |
                      {{ imagebuilder_env_ansible_user }}:{{ imagebuilder_env_ansible_password }}
                    expire: False
                    hashed: False

        when: userdata is not defined or userdata | length == 0
      - name: (BUILDPROFILE, ubuntu) create sha256 of build profile
        ansible.builtin.set_fact:
            build_profile: # noqa: var-naming
                os_iso: "{{ os.iso }}" # noqa: var-naming
                os_userdata: "{{ userdata }}" # noqa: var-naming
      - name: (BUILDPROFILE, ubuntu) create sha256 of build profile
        ansible.builtin.set_fact:
            imagebuilder_profile_hash: "{{ build_profile | to_json | hash('sha256') }}" # noqa: var-naming