---
- name: (AlmaLinux-UPLIFT) Validate inputs
  ansible.builtin.assert:
    that:
      - imagebuilder_uplift_artifact is defined
      - imagebuilder_uplift_artifact.path is defined
      - imagebuilder_target_features is defined

- name: (AlmaLinux-UPLIFT) Validate features
  ansible.builtin.assert:
    that:
      - item in ['qemu_guest_agent']
    fail_msg: >-
      Unsupported AlmaLinux uplift feature '{{ item }}'
  loop: "{{ imagebuilder_target_features }}"

- name: (AlmaLinux-UPLIFT) Boot target image
  ansible.builtin.include_role:
    name: gocallag.template_builder.imagebuilder
    tasks_from: capabilities/qemu_boot_existing
  vars:
    imagebuilder_capability_artifact:
      path: "{{ imagebuilder_uplift_artifact.path }}"

- name: (AlmaLinux-UPLIFT) Configure guest
  block:

    - name: (AlmaLinux-UPLIFT) Wait for guest
      ansible.builtin.include_role:
        name: gocallag.template_builder.imagebuilder
        tasks_from: capabilities/wait_guest

    - name: (AlmaLinux-UPLIFT) Install QEMU guest agent
      ansible.builtin.include_role:
        name: gocallag.template_builder.imagebuilder
        tasks_from: capabilities/guest_command
      vars:
        imagebuilder_guest_command: >-
          sudo dnf install -y qemu-guest-agent &&
          sudo systemctl enable qemu-guest-agent
      when:
        - "'qemu_guest_agent' in imagebuilder_target_features"

  always:

    - name: (AlmaLinux-UPLIFT) Shutdown target image
      ansible.builtin.include_role:
        name: gocallag.template_builder.imagebuilder
        tasks_from: capabilities/qemu_shutdown
      vars:
        imagebuilder_capability_artifact:
          path: "{{ imagebuilder_uplift_artifact.path }}"
