---
- name: (CAP-GUEST) Validate command
  ansible.builtin.assert:
    that:
      - imagebuilder_guest_command is defined
      - imagebuilder_guest_command | trim | length > 0
      - imagebuilder_env_qemu_ssh_port is defined

- name: (CAP-GUEST) Execute command over SSH
  ansible.builtin.shell: "{{ imagebuilder_guest_command }}"
  register: imagebuilder_guest_command_result
  changed_when: true
  delegate_to: bob_build
  # no_log: true
