---
- name: (CAP-QEMU) Prepare existing image
  ansible.builtin.include_tasks:
    file: capabilities/qemu_prepare_existing.yml

- name: (CAP-QEMU) Boot existing image
  ansible.builtin.command: >-
    {{ imagebuilder_cap_qemu_command }}
    -chardev socket,id=mon0,host=localhost,port={{ imagebuilder_env_qemu_monport }},server=on,wait=off
    -mon chardev=mon0
    -boot order=c
  async: 99999
  poll: 0
  register: imagebuilder_cap_qemu_job
  changed_when: true

- name: (CAP-QEMU) Wait for QEMU monitor
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ imagebuilder_env_qemu_monport }}"
    delay: 2
    timeout: 120
