---
- name: (CAP-GUEST) Wait for forwarded guest port
  ansible.builtin.wait_for:
    host: "{{ imagebuilder_config.builder.qemu.host }}"
    port: "{{ imagebuilder_cap_qemu_guest_port }}"
    delay: 5
    timeout: 900

- name: (CAP-GUEST) Wait for guest protocol
  ansible.builtin.include_tasks: ../waitfor.yml
  vars:
    wait_host_ip: "{{ imagebuilder_config.builder.qemu.host }}"
    wait_port: "{{ imagebuilder_cap_qemu_guest_port }}"
    wait_proto: >-
      {{ (os_type | lower == 'windows') | ternary('psrp', 'ssh') }}
    ponder: true