# ansible-lint: ignore=line-length

# RedHat-Based Systems
- name: (BUILDAUX, redhat)
  tags:
      - build_aux
  block:
      - name: (BUILDAUX, redhat) create build directories
        ansible.builtin.file:
            path: "{{ file }}"
            state: directory
            mode: "0755"
        loop_control:
            loop_var: file
        loop:
            - "{{ builder_build_basedir }}/build"
            - "{{ builder_build_basedir }}/build/mnt"
      - name: (BUILDAUX, redhat) remove existing aux ISO (if it exists)
        ansible.builtin.file:
            path: "{{ builder_build_basedir }}/build/aux.iso"
            state: absent

      - name: (BUILDAUX, redhat) create temporary iso contents dir
        ansible.builtin.file:
            path: "{{ builder_build_basedir }}/build/iso_contents"
            state: directory
            mode: "0755"

      - name: (BUILDAUX, redhat) use default ks if none provided
        ansible.builtin.set_fact:
            ks: # noqa: var-naming
                |
                  #default kickstart for redhat based systems
                  {% if (version_major | default('') | int) == 8 %}
                  repo --name=epel --baseurl=https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
                  {% endif %}
                  cdrom
                  text
                  eula --agreed
                  lang en_US.UTF-8
                  keyboard us
                  rootpw {{ builder_env_linux_admin_password }}
                  selinux --enforcing
                  firstboot --disable
                  firewall --enabled --ssh --port=22/tcp
                  authselect --enableshadow --passalgo=sha512
                  skipx
                  poweroff
                  services --disabled="kdump" --enabled="auditd,chronyd,rsyslog,sshd"
                  timezone {{ os.config.timezone }} {{ ('--isUtc') if (version_major | default('') | int) == 8 else ('--utc') if (version_major | default('') | int) >= 9 else '' }}
                  #network --hostname={{ id }}  --noipv6 --bootproto=dhcp
                  network --hostname={{ id }} --bootproto=dhcp --activate --onboot=on --noipv6
                  clearpart --all --disklabel gpt --drives=sda
                  bootloader --location mbr
                  ignoredisk --only-use=sda
                  part biosboot --fstype=biosboot --size=1 --ondisk=sda
                  partition /boot/efi --fstype=efi --label EFI  --size=200 --ondisk=sda
                  part /boot --size=1024 --ondisk sda --fstype xfs
                  part pv.1 --size 1 --grow --asprimary --ondisk sda
                  volgroup {{ os.variant | lower }} pv.1
                  # UPDATE filesystem config/sizing - Most of these are recommended for CIS
                  logvol / --fstype xfs --name lvroot --vgname {{ os.variant | lower }} --size 1024
                  logvol /home --fstype xfs --name lvhome --vgname {{ os.variant | lower }} --size 512
                  logvol /opt --fstype xfs --name lvopt --vgname {{ os.variant | lower }} --size 512
                  logvol /tmp --fstype xfs --name lvtmp --vgname {{ os.variant | lower }} --size 512
                  logvol /usr --fstype xfs --name lvusr --vgname {{ os.variant | lower }} --size 4096
                  logvol /var --fstype xfs --name lvvar --vgname {{ os.variant | lower }} --size 3172
                  logvol /var/log --fstype xfs --name=lvvarlog --vgname {{ os.variant | lower }} --size 1024
                  logvol /var/log/audit --fstype xfs --name lvvarlogaud --vgname {{ os.variant | lower }} --size 512
                  logvol swap --fstype swap --recommended --name swap --vgname {{ os.variant | lower }}

                  user --name={{ builder_env_ansible_user }} --groups=wheel --plaintext --password={{ builder_env_ansible_password }}

                  %packages --ignoremissing --excludedocs {{ ('--instLangs') if (version_major | default('') | int) == 8 else ('--inst-langs') if (version_major | default('') | int) >= 9 else '' }}=en_US.utf8
                  {% if os.variant is defined and (os.variant | lower) == 'fedora' %}
                  # Fedora-specific packages
                  {% if (version_major | default('') | int) >= 43 %}
                  # Fedora 43 and later
                  @Base
                  rsyslog
                            {% else %}
                  # Fedora versions prior to 43
                  # None Added
                            {% endif %}
                          {% elif os.variant is defined and (os.variant | lower) == 'centos' %}
                            {% if (version_major | default('') | int) == 8 %}
                  # CentOS 8-specific packages
                  @^minimal-environment
                            {% elif (version_major | default('') | int) >= 9 %}
                  # CentOS 9 and later-specific packages
                  @core
                            {% endif %}
                  # CentOS-common specific packages
                  # None Added
                          {% elif os.variant is defined and (os.variant | lower) == 'rhel' %}
                            {% if (version_major | default('') | int) == 8 %}
                              # RHEL 8-specific packages
                              @^minimal-environment
                              python39
                            {% elif (version_major | default('') | int) == 9 %}
                              # RHEL 9 and later-specific packages
                              @core
                            {% elif (version_major | default('') | int) >= 10 %}
                              # RHEL 10 and later-specific packages
                              @core
                              subscription-manager
                              subscription-manager-rhsm-certificates
                              python3-subscription-manager-rhsm
                            {% endif %}
                            # RHEL-specific packages
                            # None Added
                          {% elif os.variant is defined and (os.variant | lower) == 'almalinux' %}
                            {% if (version_major | default('') | int) == 8 %}
                              # AlmaLinux 8-specific packages
                              @^minimal-environment
                              python39
                            {% elif (version_major | default('') | int) >= 9 %}
                              # AlmaLinux 9 and later-specific packages
                              @core
                            {% endif %}
                            # AlmaLinux-specific packages
                            # None Added
                          {% elif os.variant is defined and (os.variant | lower) == 'rockylinux' %}
                            {% if (version_major | default('') | int) == 8 %}
                              # Rocky Linux 8-specific packages
                              @^minimal-environment
                              python39
                            {% elif (version_major | default('') | int) >= 9 %}
                              # Rocky Linux 9 and later-specific packages
                              @core
                            {% endif %}
                            # Rocky Linux-specific packages
                            # None Added
                        {% elif os.variant is defined and (os.variant | lower) == 'oraclelinux' %}
                            {% if (version_major | default('') | int) == 8 %}
                              # Oracle Linux 8-specific packages
                              @^minimal-environment
                              python39
                            {% elif (version_major | default('') | int) >= 9 %}
                              # Oracle Linux 9 and later-specific packages
                              @core
                            {% endif %}
                            # Oracle Linux-specific packages
                            # None Added
                          {% endif %}
                            # Common packages for all RHEL-based systems
                            audit
                            bzip2
                            chrony
                            deltarpm
                            dnf-utils
                            net-tools
                            wget
                            cloud-init
                            cloud-utils-growpart
                            rsync
                            tar
                            patch
                            vim
                            yum-utils
                            # Remove ALSA firmware
                            -a*-firmware
                            # Remove Intel wireless firmware
                            -i*-firmware
                            -open-vm-tools
                            -qemu-guest-agent

                  %end
                  # disable kdump service
                  %addon com_redhat_kdump --disable
                  %end

                  %post
                    # Disable unused filesystems
                    echo "install cramfs /bin/true" > /etc/modprobe.d/cramfs.conf
                    echo "install freevxfs /bin/true" > /etc/modprobe.d/freevxfs.conf
                    echo "install jffs2 /bin/true" > /etc/modprobe.d/jffs2.conf
                    # Set Python alternatives
                    alternatives --set python $(command -v python3)

                    #---- Install our SSH key ----
                    id -u {{ builder_env_ansible_user }} &>/dev/null || useradd -m -s /bin/bash {{ builder_env_ansible_user }}
                    mkdir -m0700 /home/{{ builder_env_ansible_user }}/.ssh/
                    echo "{{ builder_env_ansible_key }}" > /home/{{ builder_env_ansible_user }}/.ssh/authorized_keys
                    chown -R {{ builder_env_ansible_user }}:wheel /home/{{ builder_env_ansible_user }}/.ssh
                    chmod 0600 /home/{{ builder_env_ansible_user }}/.ssh/authorized_keys
                    # Ensure ansible user is in the wheel group
                    usermod -aG wheel {{ builder_env_ansible_user }}
                    echo "{{ builder_env_ansible_user }} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible
                    chmod 0440 /etc/sudoers.d/ansible

                    # Check if SELinux is enabled before running restorecon to avoid unnecessary errors
                    if [ "$(getenforce)" != "Disabled" ]; then
                      restorecon -R /home/{{ builder_env_ansible_user }}/.ssh/
                    fi

                    # Configure password quality settings
                    sed -i '/^minlen/d' /etc/security/pwquality.conf
                    echo "minlen = 14" >> /etc/security/pwquality.conf
                    sed -i '/^dcredit/d' /etc/security/pwquality.conf
                    sed -i '/^ucredit/d' /etc/security/pwquality.conf
                    sed -i '/^ocredit/d' /etc/security/pwquality.conf
                    sed -i '/^lcredit/d' /etc/security/pwquality.conf
                    echo "dcredit = -1" >> /etc/security/pwquality.conf
                    echo "ucredit = -1" >> /etc/security/pwquality.conf
                    echo "ocredit = -1" >> /etc/security/pwquality.conf
                    echo "lcredit = -1" >> /etc/security/pwquality.conf
                  %end
        when: ks is not defined or ks | length == 0

      - name: (BUILDAUX, redhat) Copy kickstart file (RedHat) to ISO contents
        ansible.builtin.copy:
            content: "{{ ks }}"
            dest: "{{ builder_build_basedir }}/build/iso_contents/ks.cfg"
            mode: "0644"
        become: true
      - name: (BUILDAUX, redhat) Copy kickstart file (RedHat) to http directory
        ansible.builtin.copy:
            content: "{{ ks }}"
            dest: "{{ builder_build_httpdir }}/ks.cfg"
            mode: "0644"
        become: true

      - name: (BUILDAUX, redhat) Build aux ISO from contents (label OEMDRV)
        ansible.builtin.command: >
          genisoimage -output aux.iso -volid OEMDRV -joliet -rock .
        args:
            chdir: "{{ builder_build_basedir }}/build/iso_contents"
            creates: "{{ builder_build_basedir }}/build/aux.iso"
        register: mkiso # noqa: var-naming
        failed_when: mkiso.rc != 0

      - name: (BUILDAUX, redhat) Move aux ISO to build directory
        ansible.builtin.command: >
          mv {{ builder_build_basedir }}/build/iso_contents/aux.iso {{ builder_build_basedir }}/build/aux.iso
        args:
            creates: "{{ builder_build_basedir }}/build/aux.iso"

      - name: (BUILDAUX, redhat) Remove temporary ISO contents directory
        ansible.builtin.file:
            path: "{{ builder_build_basedir }}/build/iso_contents"
            state: absent
        become: true
      - name: (BUILDAUX, redhat) create sha256 of build profile
        ansible.builtin.set_fact:
            build_profile: # noqa: var-naming
                os_iso: "{{ os.iso }}" # noqa: var-naming
                os_ks: "{{ ks }}" # noqa: var-naming
      - name: (BUILDAUX, redhat) create sha256 of build profile
        ansible.builtin.set_fact:
            profile_hash: "{{ build_profile | to_json | hash('sha256') }}" # noqa: var-naming
