# Alma Linux Systems
- name: (PATCHING-CLEANUP) Cleanup Alma Linux
  when: ansible_facts['os_family'] | lower == "redhat" and ansible_facts['distribution'] | lower == "almalinux"
  block:
    - name: (PATCHING-CLEANUP, alma) Clean dnf cache
      ansible.builtin.command: dnf clean all
      register: imagebuilder_dnf_clean
      failed_when: imagebuilder_dnf_clean.rc != 0
      changed_when: false
      become: true
      delegate_to: "{{ delegate | default(omit) }}"
