---
- name: (GLUE-PATCHING) Execute OS patching implementation
  ansible.builtin.include_role:
    name: "{{ os.plugin }}"
    tasks_from: patching.yml
  vars:
    imagebuilder_patching_location: >-
      {{ imagebuilder_glue_task_vars.location | default('internet') }}
  tags:
    - build_customise
  