---
- name: ALMA-8.10 Build
  hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars_files:
    - images/almalinux/almalinux-8.10.yml

  vars:
    imagebuilder_targets:
      - plugin: gocallag.imagebuilder_target.proxmox
      # - plugin: gocallag.imagebuilder_target.vsphere

  roles:
    - gocallag.template_builder.imagebuilder
