---
- name: CENTOS_9S    # noqa: fqcn[keyword]
  hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars:
    id: centos-9.s
    os:
      config:
        disks:
          - 50
        timezone: Australia/Melbourne
        nicdriver: e1000
      # iso: https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso
      iso: http://192.168.1.161:8180/centos/CentOS-9/CentOS-Stream-9-20260630.2-x86_64-dvd1.iso
      checksum: 6ed2fac1f1b7f0279b1f5eda1381cc0179775a6649c27d294ae5da4b059d1220
      console_boot: |
        <up><wait><tab><wait> inst.text inst.ks=http://{{ imagebuilder_localip }}:{{ imagebuilder_localport }}/ks.cfg<enter>

  collections:
    - gocallag.template_builder
  roles:
    - imagebuilder
    - target_proxmox
    # - target_vsphere
