---
- name: CENTOS_10S    # noqa: fqcn[keyword]
  hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars:
    id: centos-10.s
    os:
      config:
        disks:
          - 20
        timezone: Australia/Melbourne
        nicdriver: e1000
      # iso: https://mirror.aarnet.edu.au/pub/centos-stream/10-stream/BaseOS/x86_64/iso/CentOS-Stream-10-latest-x86_64-dvd1.iso
      iso: http://192.168.1.161:8180/centos/CentOS-10/CentOS-Stream-10-20251201.0-x86_64-dvd1.iso
      checksum: 8548643552a939c189b88cc8bf7100846ffad240ed11b438561f118b2bed49d3
      console_boot: |
           <up>e<down><down><end> inst.text inst.ks=http://{{ imagebuilder_localip }}:{{ imagebuilder_localport }}/ks.cfg<leftCtrlOn>x<leftCtrlOff>

  collections:
    - gocallag.template_builder
  roles:
    - imagebuilder
    - target_proxmox
