---
- name: FEDORA-44 Build
  hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars_files:
    - images/fedora/fedora-44.yml

  vars:
    imagebuilder_targets:
      - plugin: gocallag.imagebuilder_target.proxmox
      # - plugin: gocallag.imagebuilder_target.vsphere

  roles:
    - gocallag.template_builder.imagebuilder
