---
- hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars_files:
    - "images/oracle/ol-10.1.yml"

  collections:
    - gocallag.template_builder

  roles:
    - imagebuilder
