---
- hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars:
    id: rocky-9.8
    os:
      config:
        disks:
          - 20
        timezone: Australia/Melbourne
        nicdriver: e1000
      iso: http://192.168.1.161:8180/rocky/9/Rocky-9.8-x86_64-dvd.iso
      checksum: d2bcbb64c2d67511adf80d40cd9543391a33aea5860a355b1d26d7f55236d01f
      console_boot: |
          <up><wait><tab><wait> inst.text inst.ks=http://{{ imagebuilder_httpip }}:{{ imagebuilder_localport }}/ks.cfg<enter>
  collections:
    - gocallag.template_builder
  roles:
    - imagebuilder
    - target_proxmox
    # - target_vsphere
