---
- name: ROCKY-10.2 Build
  hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars_files:
    - images/rockylinux/rockylinux-10.2.yml

  vars:
    imagebuilder_targets:
      - plugin: gocallag.imagebuilder_target.proxmox
      # - plugin: gocallag.imagebuilder_target.vsphere

  roles:
    - gocallag.template_builder.imagebuilder
