---
- hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars:
    id: rocky-10.2
    os
      config:
        disks:
          - 20
        timezone: Australia/Melbourne
        nicdriver: e1000
      iso: http://192.168.1.161:8180/rocky/10/Rocky-10.2-x86_64-dvd1.iso
      # iso: https://download.rockylinux.org/pub/rocky/10.0/isos/x86_64/Rocky-10.0-x86_64-dvd
      checksum: 16ca9c96cdb221ba6e1f68579f21bd69fd8da81c6a921d9068949796f91c8feb
      console_boot: |
           <up>e<down><down><end> inst.text inst.ks=http://{{ imagebuilder_localip }}:{{ imagebuilder_localport }}/ks.cfg<leftCtrlOn>x<leftCtrlOff>

  collections:
    - gocallag.template_builder
  roles:
    - imagebuilder
    - target_proxmox
    # - target_vsphere
