---
- name: UBUNTU_2204    # noqa: fqcn[keyword]
  hosts: "{{ run_on | default('localhost') }}"
  gather_facts: false
  become: false

  vars:
    id: ubuntu-2204
    useauxiso: true
    os:
      config:
        disks:
          - 50
      iso: http://192.168.1.161:8180/canonical/Ubuntu-2204/ubuntu-22.04.5-live-server-amd64.iso
      checksum: 9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0
      console_boot: |
          e<down><down><down><end><backspace><backspace><backspace><backspace> autoinstall<leftCtrlOn>x<leftCtrlOff>

  collections:
    - gocallag.template_builder
  roles:
    - imagebuilder
    - target_proxmox
