---
- name: (PROXMOX) Validate configuration
  ansible.builtin.assert:
    that:
      - imagebuilder_artifact is defined
      - imagebuilder_artifact.id is defined
      - imagebuilder_artifact.path is defined

      - imagebuilder_config.targets.proxmox is defined
      - imagebuilder_config.targets.proxmox.server is defined
      - imagebuilder_config.targets.proxmox.username is defined
      - imagebuilder_config.targets.proxmox.password is defined
      - imagebuilder_config.targets.proxmox.storage is defined
      - imagebuilder_config.targets.proxmox.node is defined

    fail_msg: "(PROXMOX) Missing required Proxmox configuration"

- name: (PROXMOX) Resolve configuration
  ansible.builtin.set_fact:
    imagebuilder_proxmox:
      server: "{{ imagebuilder_config.targets.proxmox.server }}"
      username: "{{ imagebuilder_config.targets.proxmox.username }}"
      password: "{{ imagebuilder_config.targets.proxmox.password }}"
      storage: "{{ imagebuilder_config.targets.proxmox.storage }}"
      node: "{{ imagebuilder_config.targets.proxmox.node }}"
  no_log: true

- name: (PROXMOX) Define runtime state
  ansible.builtin.set_fact:
    imagebuilder_proxmox_vm_name: "template-{{ imagebuilder_artifact.id }}"
    imagebuilder_proxmox_bridge: "vmbr0"
    imagebuilder_proxmox_cpu: "host"
    imagebuilder_proxmox_cores: 1
