---

- name: (GLUE-PATCHING) Include patching role
  ansible.builtin.include_tasks: "patching/main.yml"
  vars:
    sub_tasks: "{{ imagebuilder_glue_task_vars.sub_tasks | default(omit) }}" # noqa: var-naming
    location: "{{ imagebuilder_glue_task_vars.location | default(omit) }}" # noqa: var-naming
    delegate: bob_build
  tags:
    - build_customise
