---
- name: (ORACLE-UPLIFT) Validate inputs
  ansible.builtin.assert:
    that:
      - imagebuilder_uplift_artifact is defined
      - imagebuilder_uplift_artifact.path is defined
      - imagebuilder_target_features is defined

- name: (ORACLE-UPLIFT) Validate features
  ansible.builtin.assert:
    that:
      - item in ['qemu_guest_agent']
    fail_msg: "Unsupported Oracle Linux uplift feature '{{ item }}'"
  loop: "{{ imagebuilder_target_features }}"

- name: (ORACLE-UPLIFT) Boot target image
  ansible.builtin.include_role:
    name: gocallag.template_builder.imagebuilder
    tasks_from: capabilities/qemu_boot_existing.yml
  vars:
    imagebuilder_qemu_image: "{{ imagebuilder_uplift_artifact.path }}"

- name: (ORACLE-UPLIFT) Configure guest
  block:

    - name: (ORACLE-UPLIFT) Wait for Oracle Linux
      ansible.builtin.include_role:
        name: gocallag.template_builder.imagebuilder
        tasks_from: capabilities/wait_guest.yml

    - name: (ORACLE-UPLIFT) Install QEMU guest agent
      ansible.builtin.include_role:
        name: gocallag.template_builder.imagebuilder
        tasks_from: capabilities/guest_command.yml
      vars:
        imagebuilder_guest_command: >-
          sudo dnf install -y qemu-guest-agent &&
          sudo systemctl enable qemu-guest-agent
      when:
        - "'qemu_guest_agent' in imagebuilder_target_features"

  always:

    - name: (ORACLE-UPLIFT) Shutdown target image
      ansible.builtin.include_role:
        name: gocallag.template_builder.imagebuilder
        tasks_from: capabilities/qemu_shutdown.yml