# set a whole bunch of variables for the build process - we set them all in advance to avoid multiple set_fact calls during the build which can cause performance issues with Ansible

imagebuilder_id_prefix: "{{ id | regex_replace('^(.*?)-.*$', '\\1') }}"   # alma-9.8 -> alma
imagebuilder_id_base: "{{ id | regex_replace('(\\.\\d+)$', '') }}"  # alma-9.8 -> alma-9
imagebuilder_id_version: "{{ id | regex_replace('^.*-', '') }}" # alma-9.8 -> 9.8
imagebuilder_env_qemu_ssh_port: "{{ 10222 + (imagebuilder_port_offset | default(0) | int) }}"
imagebuilder_env_qemu_psrp_port: "{{ 5986 + (imagebuilder_port_offset | default(0) | int) }}"
imagebuilder_env_qemu_monport: "{{ 4445 + (imagebuilder_port_offset | default(0) | int) }}"
version_major: "{{ id | regex_replace('^.*-(\\d+)\\..*$', '\\1') | int }}" # noqa: var-naming
version_minor: "{{ id | regex_replace('^.*-\\d+\\.(\\d+).*$', '\\1') | int }}" # noqa: var-naming

imagebuilder_path_basedir: "{{ imagebuilder_config.builder.build_path }}/{{ imagebuilder_id_base }}"
imagebuilder_path_httpdir: "{{ imagebuilder_path_basedir }}/http"
imagebuilder_path_auxdir: "{{ imagebuilder_path_httpdir }}/aux"
imagebuilder_path_imagedir: "{{ imagebuilder_path_basedir }}/build"
imagebuilder_path_downloadsdir: "{{ imagebuilder_path_basedir }}/downloads"
imagebuilder_path_mntdir: "{{ imagebuilder_path_imagedir }}/mnt"
imagebuilder_path_savedir: "{{ imagebuilder_path_basedir }}/images"

imagebuilder_build_id: "{{ imagebuilder_id_base }}"
imagebuilder_build_format: qcow2

imagebuilder_build_iso: "{{ imagebuilder_path_downloadsdir }}/{{ os.iso | basename }}"
imagebuilder_build_aux: "{{ imagebuilder_path_auxdir }}/{{ imagebuilder_build_id }}.iso"


imagebuilder_build_disks: "{{ os.config.disks }}"
imagebuilder_build_kickstart: "{{ imagebuilder_env_build_path }}/{{ imagebuilder_id_base }}/ks.cfg"
imagebuilder_build_ram: "{{ imagebuilder_env_build_memory | default(2048) }}"
imagebuilder_build_vcpus: "{{ imagebuilder_env_build_cpu | default(2) }}"
# imagebuilder_build_output: "build/{{ imagebuilder_id_base }}.qcow2"

# imagebuilder_aux_dir: "{{ imagebuilder_build_basedir }}/aux"
# imagebuilder_iso_file: "{{ imagebuilder_build_basedir }}/build/{{ imagebuilder_id_base }}.iso"
wait_host: "{{ imagebuilder_env_qemu_ip | default('localhost') }}" # noqa: var-naming
wait_port: "{{ (os_type | lower == 'linux') | ternary(imagebuilder_env_qemu_ssh_port, imagebuilder_env_qemu_psrp_port) }}" # noqa: var-naming
wait_proto: "{{ (os_type | lower == 'windows') | ternary('psrp', 'ssh') }}" # noqa: var-naming
imagebuilder_localip: "{{ imagebuilder_env_qemu_ip | default('localhost') }}"
imagebuilder_restored_from_image: false
