---
- name: Windows | Initialise patch pass
  ansible.builtin.set_fact:
    imagebuilder_windows_patch_pass: 0

- name: Windows | Converge Windows updates
  ansible.builtin.include_tasks:
    file: patch_pass.yml
