- name: (BANNER) Display banner
  ansible.builtin.debug:
    msg:
      - "{{ top }}"
      - "{{ side }} {{ message }} {{ side }}"
      - "{{ bottom }}"
  vars:
    message: "{{ imagebuilder_banner_message | default('') }}"
    width: "{{ message | length + 2 }}"
    top: "{{ '┌' ~ ('─' * (width - 2) | int) ~ '┐' }}"
    bottom: "{{ '└' ~ ('─' * (width - 2) | int) ~ '┘' }}"
    side: "│"
  when: message | length > 0
